[package]
name = "field_validator_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
[dependencies]
syn = {workspace = true}
quote = {workspace = true}
proc-macro2 = "1.0"
field_validator = { path = "../field_validator" }
